package values;

public enum CardType {
    INVALID,
    GAME,
    PLAYER,
    HERO,
    MINION,
    SPELL,
    ENCHANTMENT,
    WEAPON,
    ITEM,
    TOKEN,
    HERO_POWER,
    BLANK,
    GAME_MODE_BUTTON,
    MOVE_MINION_HOVER_TARGET,
    LETTUCE_ABILITY,
    BATTLEGROUND_HERO_BUDDY,
    LOCATION,
    BATTLEGROUND_QUEST_REWARD
}
